parameters:
#    interfaz_music_db_admin.example.class: Interfaz\MusicDBAdminBundle\Example

services:
#    interfaz_music_db_admin.example:
#        class: %interfaz_music_db_admin.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
